services:
  nginx:
    image: nginx:latest
    volumes:
      - ./deploy/etc/nginx/templates:/etc/nginx/templates
      - ./deploy/etc/nginx/tls:/etc/nginx/tls
      - ./deploy/etc/nginx/logs:/etc/nginx/logs
    ports:
      - 80:80
      - 443:443
    environment:
      - NGINX_PROXY_HOST=ecssapp
      - NGINX_PROXY_PORT=3000
    links:
      - ecssapp:ecssapp

  ecssapp:
    image: hn275/ecss-locker:latest
    container_name: ecss-locker-app
    environment:
      - JWT_SECRET
      - ADMIN_PASSWORD
      - GMAIL_USER
      - GMAIL_PASSWORD
      - ORIGIN
      - MYSQL_HOST
      - MYSQL_PASSWORD
      - MYSQL_USER
      - MYSQL_PORT
      - MYSQL_DATABASE

  ecssdb:
    image: mysql:8.4.0
    container_name: ecss-locker-db
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
      - MYSQL_USER
      - MYSQL_DATABASE
    volumes:
      - ./.mysql/data/:/var/lib/mysql/
      - ./deploy/:/home/
    ports:
      - 3306:3306
